name: "Install SoX and add to PATH"
description: "Install SoX and add to PATH"
runs:
  using: "composite"
  steps:
    - run: |
        set -ex
        curl -sSLO https://github.com/coqui-ai/STT/releases/download/v0.10.0-alpha.7/sox-14.4.2-win32.zip
        "C:/Program Files/7-Zip/7z.exe" x -o`pwd`/bin/ -tzip -aoa sox-14.4.2-win32.zip
        rm sox-*zip
        echo "`pwd`/bin/sox-14.4.2/" >> $GITHUB_PATH
      shell: bash
