name: "Host build lib"
description: "Host build of lib"
inputs:
  flavor:
    description: "Build flavor"
    required: true
runs:
  using: "composite"
  steps:
    - run: ./ci_scripts/host-build.sh ${{ inputs.flavor }}
      shell: bash
