name: "Setup TensorFlow"
description: "Setup TensorFlow Build"
runs:
  using: "composite"
  steps:
    - run: ./ci_scripts/tf-setup.sh
      shell: bash
    - run: echo "${DS_ROOT_TASK}/bin" >> $GITHUB_PATH
      shell: bash
