name: "Tests execution"
description: "Running tests"
inputs:
  runtime:
    description: "Runtime to use for running test"
    required: true
  model-kind:
    description: "Running against CI baked or production model"
    required: true
<<<<<<< HEAD
  bitrate:
    description: "Bitrate for testing"
=======
<<<<<<< HEAD
  bitrate:
    description: "Bitrate for testing"
=======
  samplerate:
    description: "Sample rate for testing"
>>>>>>> coqui-ai-main
>>>>>>> 94b13b64c30dd1349c6e325dba22877620ef914b
    required: true
  chroot:
    description: "Run using a chroot"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        set -xe

        build="_tflite"

        model_kind=""
        if [ "${{ inputs.model-kind }}" = "prod" ]; then
          model_kind="-prod"
        fi

        prefix="."
        if [ ! -z "${{ inputs.chroot }}" ]; then
          prefix="${{ inputs.chroot }}"
        fi

<<<<<<< HEAD
        ${prefix}/ci_scripts/${{ inputs.runtime }}${build}-tests${model_kind}.sh ${{ inputs.bitrate }}
=======
<<<<<<< HEAD
        ${prefix}/ci_scripts/${{ inputs.runtime }}${build}-tests${model_kind}.sh ${{ inputs.bitrate }}
=======
        ${prefix}/ci_scripts/${{ inputs.runtime }}${build}-tests${model_kind}.sh ${{ inputs.samplerate }}
>>>>>>> coqui-ai-main
>>>>>>> 94b13b64c30dd1349c6e325dba22877620ef914b
      shell: msys2 {0}
