name: "Lints"
on:
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  training-unittests:
    name: "Lin|Training unittests"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pyver: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Run training unittests
        run: |
          sudo apt-get install -y --no-install-recommends libopusfile0 libopus-dev libopusfile-dev
          ./ci_scripts/train-unittests.sh

  pre-commit-checks:
    name: "Lin|Pre-commit checks"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run pre-comit checks
        run: |
          python .pre-commit-2.11.1.pyz run --all-files
